name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # укажите нужную версию Python

    - name: Install dependencies
      run: make setup

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test
